[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solamm = "8PvHhUn7m3wGk1Gjd8SLyok2SsY4hJt8gddVbksGqV7u"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
