[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solamm = "9RnLR4wcfRqNc7abzqbTxK18Z8Rwv82Y9f4d5Zn36trn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
